version: "3.9"

services:
  # GATEWAY for GraphQL
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: always
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: docker
    depends_on:
      - users

  # USERS service
  users:
    build:
      context: .
      dockerfile: ./users/Dockerfile
    container_name: users
    restart: always
    environment:
      RUN_MODE: docker
    volumes:
      - ./users/environments/:/app/environments/:Z
    ports:
      - "8000:8000"

  # LEAGUES service
  leagues:
    build:
      context: .
      dockerfile: ./leagues/Dockerfile
    container_name: leagues
    restart: always
    environment:
      RUN_MODE: docker
    volumes:
      - ./leagues/environments/:/app/environments/:Z
    ports:
      - "8001:8001"

  # TEAMS service
  teams:
    build:
      context: .
      dockerfile: ./teams/Dockerfile
    container_name: teams
    restart: always
    environment:
      RUN_MODE: docker
    volumes:
      - ./teams/environments/:/app/environments/:Z
    ports:
      - "8002:8002"

  # PLAYERS service
  players:
    build:
      context: .
      dockerfile: ./players/Dockerfile
    container_name: players
    restart: always
    environment:
      RUN_MODE: docker
    volumes:
      - ./players/environments/:/app/environments/:Z
    ports:
      - "8003:8003"


### GENERATORS
  gen_names:
    build:
      context: ./generators/names
#      dockerfile: ./generators/names/Dockerfile
    container_name: gen_names
    restart: always
    volumes:
      - ./generators/names/models/:/app/models/:Z
    ports:
      - "9000:9000"